spring.application.name=AdministratorBussiness

spring.datasource.url=jdbc:mysql://192.168.1.58:3306/bussiness
spring.datasource.username=joaquin
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

sip.api.base-url=http://v4.voz.com:3030
sip.api.token=3eUeeudFtG3tBMoE6X5azlVe5
sip.api.user=soportevcuatro131


